# Generated by Django 5.2.7 on 2025-10-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
