# Generated by Django 5.2.7 on 2025-10-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_appointment_app', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
