# Generated by Django 5.2.7 on 2025-10-26 04:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_appointment_app', '0004_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Credentials',
        ),
    ]
