# Generated by Django 5.2.7 on 2025-10-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_appointment_app', '0006_appointment_user_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
